development:
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:
  encoding: utf8
  database: localeyes_development

test:
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:
  encoding: utf8
  database: localeyes_test

staging:
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:
  encoding: utf8
  database: localeyes_staging

production:
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:
  encoding: utf8
  database: localeyes
