test:
  host: localhost
  database: cal_test

development:
  host: localhost
  database: cal_development

staging:
  host: localhost
  database: cal_staging

production:
  host: localhost
  database: localeyes
